//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Otomasyon_WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaynaklar
    {
        public int kaynak_id { get; set; }
        public string kaynak_ad { get; set; }
        public string kaynak_yazar { get; set; }
        public string kaynak_yayınevi { get; set; }
        public Nullable<int> kaynak_sayfasayisi { get; set; } //nullable: null olabilir demek.
        public Nullable<System.DateTime> kaynak_basımtarihi { get; set; }
        public string kaynak_türü { get; set; }
    }
}
